### ISSUE TITLE
Support TUN/TAP proxy as an inbound.

### ISSUE THREAD

**Issue by v2ray** [v2ray/Planning#1]

**Comment by sinfere** [comment]
I think this is more likely a feature for client

TUN/TAP is just a tunnel, process IP Packet is a small work, the hard part is the protocol, it's better to let client implement this feature

**Comment by v2ray** [comment]
V2Ray's philosophy is to have everything integrated, easy to setup and with low overhead. On mobile, this integration saves one layer in the proxy chain, deduces both memory usage and disk consumption.

**Comment by sinfere** [comment]
It's ugly to integrate everything, means more and more tradeoff

**Comment by sinfere** [comment]
There remains so much work to do，stability / connection profiling / upstream load balance / connection error handling / mKCP - BBR speed measurement

**Comment by sinfere** [comment]
On iOS，network extension has done this work, it provides packetFlow as a tun, it's elegant, it's easy to implement customized vpn protocol, using NEKit

**Comment by testcaoy7** [comment]
Use tun2socks.

**Comment by owoin** [comment]
_使用 [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/) 从我的 HM NOTE 1LTETD 发送_

**Comment by VictoriaRaymond** [comment]
Closing in favor of https://github.com/eycorsican/go-tun2socks
