### ISSUE TITLE
Support for AEAD in Shadowsocks protocol

### ISSUE THREAD

**Issue by astrataro** [v2ray/Planning#11]
Shadowsocks decided to add AEAD in [SIP004](https://github.com/shadowsocks/shadowsocks-org/issues/30). Any plan to synchronize the changes?

**Comment by v2ray** [comment]
There is still some more discussions in SIP007. I'd like to wait until the whole design gets settled.

**Comment by htfy96** [comment]
The latest shadowsocks-android has removed OTA(https://github.com/shadowsocks/shadowsocks-android/issues/1143) and added support for AEAD. Is there any further plan in v2ray regarding AEAD?

**Comment by v2ray** [comment]
The plan is to add a new inbound/outbound pair, namely 'shadowsocks-aead'. The new one works in parallel with the existing one.

**Comment by DarienRaymond** [comment]
Will be added in V2Ray 3.0. New ciphers are added in the existing Shadowsocks inbound/outbound.
