### ISSUE TITLE
Specification of framework and API / module / plugin?

### ISSUE THREAD

**Issue by astrataro** [v2ray/Planning#12]
V2ray seems to be the most promising socks5 proxy framework in terms of modularity. I suppose that V2ray was designed in this way according to [this comment](https://github.com/shadowsocks/shadowsocks-org/issues/28#issuecomment-270656525). If so, I think it is the right time to take a discussion with other main socks proxy developers, i.e. Shadowsocs devs, to at least make a draft specification of how V2ray framework is made and decide the API for each protocol libraries and plugins. I make this suggestion at this moment for these reasons:

1. V2ray can keep focus on framework development, and all the protocols (including Vmess, Shadowsocks and other potential protocols) will be able to keep eyes on protocol implementation, rather than building up usable proxy tools and implementing same features like obfs/kcp by themselves. They can simply implement libraries and let v2ray to invoke. It would be easier to implement libvmess, libshadowsocks, libfuturesocks as proxy protocols, and libobfs, libkcp as plugins. V2ray will be a great test bed for them.

2. Seperating development of framework and protocols / plugins would make future refinement much easier. It is also helpful for developing clients on various platforms.

3. If the implementations of protocols and plugins strictly follow specifications, it would be less pain in the future to adjust them in v2ray, or even other future frameworks.

4. Currently, Shadowsocks, the most wide-spread socks proxy protocol, is being in a phase of evolution. While plugins like obfs started just for a short time. It is the best time to talk with other devs and decide how API is made without sacrificing features and/or performance.

**Comment by DarienRaymond** [comment]
API is finished: https://github.com/v2ray/v2ray-core/tree/master/app/commander , although lack of documentation.

There is no official plan for plugin / extension system anytime soon. However, the current design of V2Ray allows external feature to be registered and run in a V2Ray runtime. One may write a plugin system on his/her own and build a customized version to support such feature.
