### ISSUE TITLE
TLS Enhancement: Support "HTTP Public Key Pinning"

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/Planning#15]
Lets Encrypt is a great tool to establish your own PKI but it is not as secure as commercial CA. 
Please add support for "HTTP Public Key Pinning" (RFC 7469) to avoid certain risks like MITM attacks with forged certificates.

**Comment by v2ray** [comment]
This RFC is for HTTP. Do you mean to add this feature to WebSocket?

**Comment by testcaoy7** [comment]
@v2ray There is no doubt that secure WebSocket (wss) can use this feature. But I think TCP VMess transport can use this feature as well if you do a HTTP handshake before using VMess protocol or warp VMess into HTTP request and response.

**Comment by DarienRaymond** [comment]
There is no plan for this.
