### ISSUE TITLE
IP 包伪装

### ISSUE THREAD

**Issue by oing9179** [v2ray/Planning#16]
有些 IPS 会对流量较大的 UDP 包进行 QoS <sup>[1][1]</sup>，导致的现象就是 客户端上行100%丢包 下行照常，但是 `ping` 包倒是能正常到达。
于是我试了试运行多个 `ping` 以1ms的速度发包，十几分钟后仍然能接收到来自服务器的 ping reply。初步判断这个 ISP 不会对 ICMP echo-reply 进行 QoS。
总结一下 IP包(ICMP 伪装) 的优点：

1. 有效载荷(payload)比例不会太低
2. 可以过(bypass)一些针对大流量 UDP 包的 QoS

References:

1. [Kcp用着用着偶尔就会断开{伪解决方案} #228][1]

[1]: https://github.com/xtaci/kcptun/issues/228

**Comment by oing9179** [comment]
#1

**Comment by wangyu-** [comment]
用这个tunnel套在前面就可以给udp流量加上tcp或者icmp header。这样就不用每个应用单独实现这个功能了。
https://github.com/wangyu-/udp2raw-tunnel

**Comment by DarienRaymond** [comment]
暂时没有这方面的计划，V2Ray依然只注重TCP和UDP的数据。
