### ISSUE TITLE
Support of splitting config file

### ISSUE THREAD

**Issue by nicholascw** [v2ray/Planning#17]
**As people knows V2Ray now have very heavy single-file configuration system which default located `/etc/v2ray/config.json`. Since the config shows in directory rather than a single file in `/etc/` ,maybe it is time to migrate to a multiple file configuration system.**

Personnally I recommand the following options.

I. Split the current single file into fixed sections like `router.json,inbound.json,outbound.json`, etc, directly put into /etc/v2ray/

II. Split as conf.avail and conf.enabled which would support symbol link and much more feature, and could be better supporting multiple users' system.

for example `/etc/v2ray/conf.avail/` could have 1`0-transport.json, 20-router.json, 21-user1.json, 22-user2.json`,(_could be inbound/outbound detour_).

which helps switch state and provide a more dynamic environment.

**Comment by DarienRaymond** [comment]
和 https://github.com/v2ray/Planning/issues/20 同理，V2Ray Core 不关心配置文件格式，如果你想支持更多的格式，可以自己写程序来支持。如果证明可行的话，core 中会添加逻辑来调用你的程序。
