### ISSUE TITLE
Add Support for libucl like configure file, and make new parser adherence to protobuf definition and eliminate additional intermediate progressing step   

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/Planning#20]
对于libucl类的配置文件，golang 有自己的[支持库](https://github.com/lytics/confl)。

libucl类配置文件兼容多种配置文件，并且可以比较简单的处理目前正变得更加复杂的配置文件，并且提高配置文件的可读性并降低修改成本。

同时，通过修改配置文件的格式让配置文件的结构和pb定义相同，减少未来在添加新功能时需要的工作量。

**Comment by DarienRaymond** [comment]
最终目标都是序列化成 pb，文本格式的配置文件长什么样，core 并不是很关心。如果你想做的话，可以开一个 repo 做一个单独的程序，输入是自定义的配置文件，输出是 pb，然后 core 来调用就行了

怕麻烦的话可以直接 commit 到 ext 里面。
