### ISSUE TITLE
[RFC] v2ray log auto rotate , keep 30days log seems enough 

### ISSUE THREAD

**Issue by ghost** [v2ray/Planning#21]
[RFC] v2ray log auto rotate , keep 30days log seems enough . 
Do not let the log file growing and no control

**Comment by yamada95** [comment]
@netroby How do you think have another tool such as logrotate to take this job?

**Comment by ghost** [comment]
Hard to configure it right. If v2ray built in can rotate it's log, we do not need logrotate.

**Comment by kmdgeek** [comment]
How about this: let V2ray add a date area in output filename, for example, `/tmp/v2ray/access_${date}.log`, and then output filename will look like `access_20170731.log`. In this way, it will be easy to delete logs manually or with cron job.

**Comment by DarienRaymond** [comment]
The plan will be making V2Ray interoperable with tools like logrotate. There is no reason to implement the rotating logic inside V2Ray.

**Comment by DarienRaymond** [comment]
As of V2Ray 3.16, the logger function can be restarted through a gRPC call.

Here is a quick example:

1. Enable V2Ray [api feature](https://www.v2ray.com/chapter_02/api.html) and LoggerService. [example](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)
1. Run V2Ray
1. Run logrotate to backup old log file and create a new log file.
1. Make a gRPC call to [LoggerService.RestartLogger](https://github.com/v2ray/v2ray-core/blob/master/app/log/command/config.proto#L17). The RPC call will restart V2Ray's internal logger, hence it will write to the new log file.
    * The RPC call may be invoked from `v2ctl api --server=<server_address> LoggerService.RestartLogger ""`
1. After the RPC call succeeds, V2Ray will continue to write logs into the new file.
