### ISSUE TITLE
V2Ray.Com Upgrade Requirement

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/Planning#22]
The website needs to grow as the project grows. Requirements are:

1. Static site.
    1. All content must be committed Github.
    1. No privacy issue like password.
1. Dynamic multiple sections.
    1. Each section for one component in V2Ray, such as core, UI client, configurator, etc.
    1. Each section may have its own sub-menu.
1. Morden design.
    1. Support major browser and mobile.
    1. Good support for displaying source code on the website.
    1. Good support for links to a particular section or sub-section.
    1. Good support for multiple languages.
1. Easy generation from source code to website
    1. Preferably based on existing, well-maintained website engine.

**Comment by ghost** [comment]
Participate in this project and join your team?

**Comment by Integ** [comment]
How to collaborate with you guys?

**Comment by DarienRaymond** [comment]
@Nobitasean Yes. If you want to.

@Integ Use the issue and project section here, or telegram: https://www.v2ray.com/chapter_01/issue.html

**Comment by ghost** [comment]
@DarienRaymond What program language is used?

**Comment by DarienRaymond** [comment]
@Nobitasean The website? No preference.

**Comment by DarienRaymond** [comment]
No time for this work.
