### ISSUE TITLE
Is there any plan to add dns cache in the program

### ISSUE THREAD

**Issue by evvil** [v2ray/Planning#23]
when i use  "domainStrategy": "IPIfNonMatch", strategy, every domain will query remote dns server
if cache some domain fetched from the dns server, it will have a high performance

**Comment by DarienRaymond** [comment]
The DNS query result is already cached. DNS lookup will look at cache first and make a real query if no previous record is found, or previous record has expired.

See: https://github.com/v2ray/v2ray-core/blob/master/app/dns/server/server.go

**Comment by evvil** [comment]
oh, sorry, because i didn't find any document of it, i will close it.
thanks again
