### ISSUE TITLE
V2RayN's developer was resigned and a proper handling of projects is needed.

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/Planning#26]
Collected previous code:

[V2rayNG.zip](https://github.com/v2ray/Planning/files/1289457/V2rayNG.zip)

**Comment by DarienRaymond** [comment]
How about we republish the code under its original name and mark it as "unmaintained" in readme.

**Comment by xiaokangwang** [comment]
There should be an unanimous consensus on republish the source with original name and mark it as unmaintained.
 
I believe we needs to decide whether to continue distribute binary version of this this series of software and leave it unmaintained as this could lead to security issue.

**Comment by DarienRaymond** [comment]
I don't have bandwidth to set up auto-release for the project. I'd like to leave this task to the next developer.
