### ISSUE TITLE
Wildcard dns host / mutli-record

### ISSUE THREAD

**Issue by KazamaSion** [v2ray/Planning#32]
In some websites, like weibo (in overseas), bilibili, they use the CDN with same IP/IPs.  
For example:   
In Hong Kong, `www.bilibili.com`, `account.bilibili.com`, `space.bilibili.com`, etc will be resolved to `47.90.50.109`.   
In Shanghai Telecom, `comment.bilibili.com` will be resolved to: `101.227.5.220`-`101.227.5.227` (= `101.227.5.220/30` + `101.227.5.224/30`)  

Requirement:  
Support Wildcard DNS(including Regex Rules), mutli-record(including CIDR).

**Comment by DarienRaymond** [comment]
Wildcard static host will be released soon. 

Multi record is not necessary, as the IP is used mainly for routing. It doesn't provide much value if a domain has multiple IPs in such case.
