### ISSUE TITLE
希望增加一个某些url只做DNS查询的模式

### ISSUE THREAD

**Issue by daiaji** [v2ray/Planning#33]
vultr全线被pixiv ban了
那帮咸鱼说没法让pixiv的人解封
我已经几个月没去pixiv收图了
要死了
而且路由上的chinadns似乎是存在着隔三差五会使能失败问题
现在SS又已经瘫了
基本上没法指望路由器上有什么搞头了

**Comment by DarienRaymond** [comment]
请详细描述你的需求

**Comment by daiaji** [comment]
@DarienRaymond 路由里加个只对列表的url作dns解析不代理的功能 dns希望支持非标准端口的服务器

**Comment by DarienRaymond** [comment]
只解析不代理有什么意义呢？

**Comment by daiaji** [comment]
@DarienRaymond 只是想抗DNS污染而已
vultr VPS几乎所有的IP都被pixiv ban了
而直连pixiv会DNS污染
现在的情况就变成了不管代不代理都没法上pixiv了

**Comment by lsylsy2** [comment]
https://github.com/cokebar/gfwlist2dnsmasq
dns的问题让dns去解决，怎么让dns走代理或者加密就是自己配置的问题了

**Comment by daiaji** [comment]
@lsylsy2 路由上弄透明代理的时候 难不成还弄个SSR放上去做加密DNS？
v2ray做DNS不是美滋滋？
其实由于Go太大了
我是没有在路由器上用的打算
所以是在PC上用……
结果因为上面的原因 
我啊 已经半年没去Pixiv了……
然后就是gfwlist现在真的能用吗？🙃

**Comment by kingsznhone** [comment]
你不会换个小鸡？linode 搬瓦工了解一下

**Comment by VictoriaRaymond** [comment]
已解决
