### ISSUE TITLE
一个新GUI项目希望加入 Project V

### ISSUE THREAD

**Issue by 699ebe23** [v2ray/Planning#35]
这是一个用PyQt5写的一个GUI。请代为发布，并添加现在这个帐号相应PUSH权限，作为后期维护使用。

项目文件已经发到v2ray@protonmail.com

![capture](https://user-images.githubusercontent.com/34744706/34451380-95bf8630-ed5e-11e7-95a2-fbf47e5088b6.PNG)

**Comment by VictoriaRaymond** [comment]
已邀请，你可以自己创建一个新的repo并submit。
