### ISSUE TITLE
建议增加手工配置列表文件来控制路由模块的IP或域名字段，代替在主配置文件硬编码化。

### ISSUE THREAD

**Issue by Cwek** [v2ray/Planning#36]
类似geosite:cn和geoip等，v2ray是通过外置的geosite.dat来列出对应的清单，对于其他域名或地址需要在主配置文件的路由模块中设置，但是需要在配置文件硬编码、数量多时会令配置文件累赘、重启应用才能生效。建议路由模块配置新字段用于建立一个列表文件的路径，程序定时读取文件而获得里面的域名或IP，从而减少主配置文件的大小和应用的重启运行。

代码例子：
```
"route":{
  "strategy": "rules",
  "domainStrategy": "AsIs",
  "settings": {
    "rules": [
      {
        "type": "field",
        "domainFile": "/path/to/domainlist.txt", //域名文件
        "outboundTag": "direct"
      },     
    ]
  }
}
```
domainlist.txt
```
www.baidu.com
domain:google.com  #允许使用v2ray的域名匹配关键字
...
```

对于来源IP或目标IP的设置雷同。

**Comment by elvisw** [comment]
我也需要这样的功能+1，并且建议“domainFile”能够解析gfwlist的列表。

**Comment by DarienRaymond** [comment]
已修复，详见路由配置。
