### ISSUE TITLE
API for manipulating a running V2Ray process

### ISSUE THREAD

**Issue by v2ray** [v2ray/Planning#4]
The following APIs will be provided:

- [ ] Add/Remove user from a proxy
- [ ] Add/Remove an inbound / outbound

**Comment by serika00** [comment]
请问这个功能是否已经在开发，是的话开发进度如何了？

另外似乎没看到有流量统计的计划，我觉得既然要加API来管理用户，那应该是针对有大用户量需求的，如果不结合流量统计的话，恐怕不太好对这些用户进行管理，这方面的计划如何呢？

**Comment by coderfox** [comment]
Have such feature been put into development? I think I may lend a hand on it.

Is Pull-Requests available, or the API is still under discussion?

**Comment by DarienRaymond** [comment]
Done.

**Comment by t123yh** [comment]
请问是否会添加流量统计的功能？
