### ISSUE TITLE
tlsSettings增加自定义RootCAs的功能

### ISSUE THREAD

**Issue by deadblue** [v2ray/Planning#42]
拜读了一下文档和对应的源代码，目前如果想在传输层使用TLS，或者向CA申请一个证书，或者将allowInsecure设置为true。
向CA申请证书大多数是收费的，目前不收费的大概只有letsencrypt一家，但是需要每三个月更新一次证书。
而启用allowInsecure则安全性大打折扣，若遭到中间人攻击则与裸奔无异，无法达到伪装的目的。

查了一下golang的文档，tls.Config是支持自定义根证书库的：
https://golang.org/pkg/crypto/tls/#Config
```
        // RootCAs defines the set of root certificate authorities
        // that clients use when verifying server certificates.
        // If RootCAs is nil, TLS uses the host's root CA set.
        RootCAs *x509.CertPool
```

用户可以通过程序或openssl工具，自己生成一个根证书，并用它签发一个服务器证书。之后只要在client端设置信任自己生成的根证书，即可同服务器建立TLS连接。

附上自己实现的例子，希望有所帮助：
https://github.com/deadblue/letsgo/tree/master/tls

**Comment by DarienRaymond** [comment]
下一版本会支持。由于 Golang 的限制，目前这一功能在 Windows 上不可用。
