### ISSUE TITLE
增加流量统计功能（或VMess的多端口支持）

### ISSUE THREAD

**Issue by jiangzihao** [v2ray/Planning#44]
由于Vmess好像不支持多端口呀。
能添加一个根据用户来区分的流量统计功能吗？

由于合租的VPS，又是按流量计费的，大家都用一个端口不好计算谁用的多谁用的少呀

或者添加多端口支持也行，这样Linux下还可以用iptable来进行流量统计

**Comment by lsylsy2** [comment]
vmess支持多端口，准确说是v2ray支持多端口，并且在不同端口上可以运行不同协议。
请阅读文档 https://www.v2ray.com/chapter_02/01_overview.html 中 inboundDetour 部分

**Comment by jiangzihao** [comment]
已查阅到。谢谢

**Comment by DarienRaymond** [comment]
会在下一版本添加流量统计功能。
