### ISSUE TITLE
Reinforence security by disallowing blind trust of tls certificate and replace it with certificate pinning

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/Planning#46]
Currently, V2Ray allow an InsecureSkipVerify flag on tls config to be set and forgive the certificate issue. And this feature is documented as "This should be used only for testing." However, with the variety of environment and CA problems presented on host, this flag is too often abused and created an systemic security risk. 

Since V2Ray cannot show certificate in question upon the certificate error.(Or even impossible to know the exact reason of error on some Android Client), user may enable this flag to solve connectivity issue(it might some time do and hide underlying issue). This can pose significant problem on the security and invisibility of V2Ray connection and even inflict major damage to user should user entrust v2ray with important traffic.

To counteract this issue, I propose follow change to V2Ray as solution:
 
- Add "certificate_pinning" field to tlsSetting, which MAY include the SHA3-512 hash of peer certificate
- Add "publickey_pinning" field to tlsSetting, which MAY include the SHA3-512 hash of peer certificate public key
- Add "certificate_chain_pinning" field to tlsSetting, which MAY include the SHA3-512 hash of peer certificate authority OR one of the certificate in certificate trust chain
- Remove allowInsecure from json configure and ignored or set to reserve in pb config.
- When dialing tls connection, if ANY of certificate_pinning publickey_pinning certificate_chain_pinning is set, InsecureSkipVerify flag is set. After dial and before any data is sent, https://golang.org/pkg/crypto/tls/#Conn.ConnectionState is retrieved and verify against ALL of certificate_pinning publickey_pinning certificate_chain_pinning spec. Abort connection if ANY of verification is failed. And display certificate info of peer. 
- Does not and discourage of any client to automate the process of adding trust to certificate without verifying the ownership of private key. This include showing the the SHA3-512 hash of peer certificate.(Client MAY show the SHA2-256 hash of certificate), but NOT include allow user to select the certificate allow from filesystem.
- If any tls inbound is configured, AFTER the listen, the SHA3-512 hash of certificate and public key is printed. (This ensure the server have the private key)
- v2ctl or configure generate tool MAY generate the SHA3-512 hash of any certificate uploaded or on filesystem, but MUST NOT allow user to harvest the certificate or its hash by attempting connection.

The reason for choosing SHA3-512 as hash algo is that currently no tool can automate the process of generating such an hash and user must export it to filesystem before generate the hash, which is not significantly easier than copy the hash of CA or certificate from server, which encourage user to discover certificate issue and found out underlying reason and not comprise long term interest of user in exchange of dangerous convenience.

**Comment by DarienRaymond** [comment]
The proposal is way too complicated. We don't expect users to understand how SHA3 works, and how to deal with auth failures. Normal users simply don't understand how TLS certificate works, including certificate chains, CA, and public/private keys. We can't force everyone to learn these many stuff.

Closing this proposal in favor of https://github.com/v2ray/Planning/issues/42
