### ISSUE TITLE
V2Ray SDK

### ISSUE THREAD

**Issue by v2ray** [v2ray/Planning#5]
V2Ray will provide SDK in the following languages:

- C#
- Java
- Objective C
- PHP

With following functionalities:

- Protobuf-based config serialization
- gRPC server for receiving events
- gRPC client for manipulating V2Ray

**Comment by duanhai** [comment]
any updates?

**Comment by techotaku** [comment]
**C# (.Net Standard 1.5) SDK**: 
* [NuGet](https://www.nuget.org/packages/V2Ray.SDK/)  
* [GitHub](https://github.com/techotaku/v2ray-dotnet-sdk)  

@duanhai 欢迎品尝

**Comment by VictoriaRaymond** [comment]
Closing in favor of third party sdks.
