### ISSUE TITLE
Mux 和 access.log 的问题

### ISSUE THREAD

**Issue by Cwek** [v2ray/Planning#51]
日志里面，access用来记录通过v2访问的地址。而Mux是使用v1.mux.cool作为访问地址，然后再上面负载真正需要访问的地址的流量。

但是如果客户端的outbound使用了Mux的话，客户端的access只会记录到v1.mux.cool:0这个访问记录，而无法记录其负载的真正需要访问的地址。虽然可以通过看服务端的access来知道，但这会很麻烦。

所以期望access不要记录这假地址的访问，而是让Mux内部去记录真正访问地址到access的日志中。

**Comment by DarienRaymond** [comment]
你用了mux和什么协议搭配？mux/vmess这个亲儿子组合是已经修了的。

**Comment by Cwek** [comment]
新版本？现在用的是3.11，vmess/mux。

**Comment by DarienRaymond** [comment]
嗯，换最新版可以了
