### ISSUE TITLE
优化core内存

### ISSUE THREAD

**Issue by liuminglm** [v2ray/Planning#52]
ios 的kitsunebi使用core，会频繁的断，作者说是内存太大，希望core优化，减少内存，能适应ios的使用

**Comment by DarienRaymond** [comment]
Planning 不接受这样没有操作性的提议。如果你有某个特定的减少内存使用的方案，请重开这个issue并附上方案。

**Comment by MatoMA** [comment]
不使用kcp，问题应该是不大的。iOS的Network Extension只允许使用15M内存，什么都不做就差不多用了10M了，也就说给V2Ray的只有5M，正常使用V2Ray大概要4M（其他奇怪的使用方法还没测试，就是最基本的使用而已）。KCP提高速度就需要读写Buffer，所以这个两者是矛盾的，问题不可解（更何况Go本身是靠GC管理内存，即使可以解决也比较费劲）。讨论这个确实没啥意义。最好的办法应该是Kitsunebi在客户端禁掉kcp的功能设置（或者其他会引起内存问题的功能）而不是摆在那让用户浪费时间。

**Comment by ameue** [comment]
> Extension

不同iPhone内存上限还不一样，iPhone 5只有5M

**Comment by i2Ray** [comment]
> > Extension
> 
> 不同iPhone内存上限还不一样，iPhone 5只有5M

运行最简单的NetworkExtension+Go（Go就是调用最简单的打印函数），开销为4M+，所以老设备如果只有5M，可以说是不支持。
