### ISSUE TITLE
Manually configure cipher suite in tls transport.

### ISSUE THREAD

**Issue by Yaspee** [v2ray/Planning#55]

**Comment by DarienRaymond** [comment]
Please provide your reason for doing this.

**Comment by Yaspee** [comment]
* Will be more flexible in some older devices. e.g use ChaCha20-Poly1305 Cipher Suites in devices which dosen't support AES-NI.

* Users can disable insecure key exchange mechanisms as `RSA` manually on server side.

**Comment by DarienRaymond** [comment]
>Will be more flexible in some older devices. e.g use ChaCha20-Poly1305 Cipher Suites in devices which dosen't support AES-NI.

This is automatically selected.

> Users can disable insecure key exchange mechanisms as RSA manually on server side.

This should be automatic too. It would be a big trouble is insecure cipher is not disabled by default.

**Comment by Yaspee** [comment]
> This should be automatic too. It would be a big trouble is insecure cipher is not disabled by default

ref: https://golang.org/src/crypto/tls/cipher_suites.go Line 93

in golang standard tls implement, `RSA` on key exchange is not disable yet. 


* About cipher suite on older devices.

> This is automatically selected.

Agreed, don't have other questions on this.

**Comment by DarienRaymond** [comment]
> RSA on key exchange is not disable yet.

Please provide evidence that RSA is not secure.

**Comment by Yaspee** [comment]
For TLS v1.3 draft 28, RSA and DH has been removed by default.

> Static RSA and Diffie-Hellman cipher suites have been removed; all
      public-key based key exchange mechanisms now provide forward
      secrecy.

from https://tools.ietf.org/html/draft-ietf-tls-tls13-28#section-1.3

**Comment by DarienRaymond** [comment]
V2Ray 3.24 will use TLS 1.3 recommended ciphers suites by default. There will be an option to enable deprecated suites.
