### ISSUE TITLE
更简单的api

### ISSUE THREAD

**Issue by Ninzero** [v2ray/Planning#62]
目前v2ray 已经支持了一部分api了, 但是官网上说得实在太简单, 网上也没有什么相关内容。有没有可能做出类似于监听某个端口, 请求127.0.0.1的这个端口就返回所有的数据…就像v2rayX的view config.json只需要访问127.0.0.1:8070/config.json就行了一样?

**Comment by orangle** [comment]
返回所有数据是什么样的数据？ 这个表述看起来很费劲呀。

**Comment by Ninzero** [comment]
大约就是json形式返回能调用的各种数据, 当然也可以通过url包含参数的方式指定返回的数据内容

**Comment by VictoriaRaymond** [comment]
你需要这个：https://github.com/grpc-ecosystem/grpc-gateway
