### ISSUE TITLE
关于时间是否可以在客户端和服务器都加上offset

### ISSUE THREAD

**Issue by minmemory** [v2ray/Planning#63]
如果只是简单的梯子大可不必在意时区问题，但是如果需要把V2ray用于其他用途的时候就不得不去考虑这个因素，让分布于全球不同地区的客户端和服务器全部迁就一个时区，妥协的代价会有些大了
所以能不能提议增加一个offset（本地时间相对GMT的偏差），通过offset校正之后就可以解决以上问题

**Comment by VictoriaRaymond** [comment]
时区没有必要一致呀，只要对应的UTC时间一样就行了。如果是因为硬件原因走时不准的话，硬编码offset是没有意义的。

**Comment by minmemory** [comment]
好的，因为前面看到Wiki说是时间要一致但是没有写明时区是否需要统一
