### ISSUE TITLE
能否为传出及传入连接增加 mark 配置项

### ISSUE THREAD

**Issue by qnnnnez** [v2ray/Planning#66]
在 Linux 上，可以通过 setsockopt SOL_SOCKET, SO_MARK 来给 socket 设置一个 mark，之后这个 socket 发出的所有包都会带上设定的 mark 值。
这个值可以在 iptables/tc/ip rule 中用来匹配流量。

使用场景：
我有一个 VPN，想在 V2Ray 中加一个传出连接来使用这个 VPN。
这时我就可以加一个 freedom 的传出连接，把 mark 设定为 123456。
假设 VPN 的接口是 `myvpn`，那我可以这么写命令：`ip route add default dev myvpn table 114514 &&  ip rule add fwmark 123456 table 114514`

**Comment by VictoriaRaymond** [comment]
这个功能要等 Go 1.11 才能做。

另外只需要传出连接吧，传入有必要吗？

**Comment by qnnnnez** [comment]
传入连接确实可以直接根据端口号来判断，不实现也没什么问题。

**Comment by VictoriaRaymond** [comment]
会在下一版本实现传出连接的SO_MARK。
