### ISSUE TITLE
能否增加一个内置的版本检测及更新程式

### ISSUE THREAD

**Issue by Rucc1** [v2ray/Planning#68]
新版本程式可能带有一些新的 bug 修复、性能提升等；但是“总有用户不喜欢更新”，希望能增加一个在启动 v2ray instance 前检测 v2ray 是否有最新版本，如果有，则进行更新的程序。

* 对于获取新版本号，可以使用 github API

* 对于下载不顺畅的地区，可以在 JSON 中增加传递给 v2ray 更新程序的 socks 代理信息（或许可以通过用户已配置在 JSON 中、可用的 inbound socks 代理），v2ray 更新程序通过此代理下载新版程式。

**Comment by VictoriaRaymond** [comment]
这个扔给第三方做吧，多少会涉及UI之类的功能。
