### ISSUE TITLE
希望在 Freedom 中加入配置规则，IPv4 优先/ IPv6 优先

### ISSUE THREAD

**Issue by zw373** [v2ray/Planning#72]
从目前代码中看，freedom 对 UseIP 的选项下的地址选取是随机从 DNS 解析的结果选一个，而不考虑命中freedom outbound 的路由匹配规则使用的地址。这就会出现写了“若为 ipv6 地址则通过 freedom 发出”的规则，而实际通过 freedom 发出了 ipv4 包。

在国内高校普遍实行 ipv4 收费 ipv6 免费的现状下，有对两种流量分别处理的需求。

提出此 plan 的起因在此处有更详细介绍：https://github.com/v2ray/discussion/issues/36

**Comment by VictoriaRaymond** [comment]
Duplicated to https://github.com/v2ray/v2ray-core/issues/1379
