### ISSUE TITLE
Domain sniffing for HTTP and HTTPS connections

### ISSUE THREAD

**Issue by v2ray** [v2ray/Planning#8]
In the VPN scenario, client can't use SOCKS protocol with remote domain resolution, because all the traffic are send as IP packets. The DNS resolution happens before SOCKS.

Due to local DNS cache and DNS poisoning, the client may already have a poisoned DNS result before connecting to VPN. A workaround for this issue is to parse HTTP and HTTPS header to get the domain address of the request, and use the domain instead of the IP for the proxy request.

**Comment by DarienRaymond** [comment]
Implemented in V2.25.
